version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi
    env_file: ".env"
    ports:
      - "8000:8000"
    networks:
      - web
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - fastapi
    networks:
      - web

volumes:
  caddy_data:
  caddy_config:

networks:
  web:
    name: fastapi_network  # Named network for clarity