version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi
    env_file: ".env"
    ports:
      - "8000:8000"
    networks:
      - web
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always
    
networks:
  web:
    name: fastapi_network  # Named network for clarity