version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi
    env_file: ".env"
    ports:
      - "8000:8000"
    networks:
      - web
    restart: always
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./ssl:/etc/nginx/ssl
    depends_on:
      - fastapi
    networks:
      - web
    restart: always
    
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    shm_size: 2gb
    ports:
      - "4444:4444"
    networks:
      - web
    restart: always

networks:
  web:
    name: fastapi_network  # Named network for clarity